main: com.MylesAndMore.GlideGame.Main
name: GlideGame
version: 0.0.1
description: 'A Minecraft: Java Edition plugin recreating the Glide minigame from Minecraft Legacy Console Edition.'
api-version: '1.20'
load: STARTUP
author: MylesAndMore
website: https://github.com/MylesAndMore/GlideGame
depend:
  - Multiverse-Core
commands:
  start:
    description: Force starts a GlideGame with an optional world.
    usage: '§cUsage: /glidegame:start [world]'
    permission: GlideGame.start
permissions:
  GlideGame.start:
    description: Allows you to start a GlideGame.
    default: op
